---
name: concourse

# replace with `bosh status --uuid`
director_uuid: a003787d-ccb9-4138-8b1f-51f5ea976a8d

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest

stemcells:
- alias: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  os: ubuntu-trusty
  version: 3312.12

instance_groups:
- name: web
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: medium
  vm_extensions: [concourse-sg]
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # this instance group to your ELB
  stemcell: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  azs: [z1]
  networks:
    - name: private
      default: [dns, gateway]
    - name: vip
      static_ips: [52.200.30.198]
  jobs:
  - name: atc
    release: concourse
    properties:
      # replace with your CI's externally reachable URL, e.g. https://ci.foo.com
      external_url: http://concourse.kartiklunkad.com
      # replace with username/password, or configure GitHub auth
      basic_auth_username: admin
      basic_auth_password: pivotal
      postgresql_database: &atc_db atc
      bind_port: 80
  - name: tsa
    release: concourse
    properties: {}

- name: db
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: medium
  stemcell: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  # replace with a disk type from your BOSH Director's cloud config
  persistent_disk_type: large
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: postgresql
    release: concourse
    properties:
      databases:
      - name: *atc_db
        # make up a role and password
        role: admin
        password: pivotal

- name: worker
  instances: 1
  # replace with a VM type from your BOSH Director's cloud config
  vm_type: medium
  #vm_extensions:
  # replace with a VM extension from your BOSH Director's cloud config that will attach
  # sufficient ephemeral storage to VMs in this instance group.
  #- REPLACE_ME
  stemcell: bosh-vsphere-esxi-ubuntu-trusty-go_agent
  azs: [z1]
  networks: [{name: private}]
  jobs:
  - name: groundcrew
    release: concourse
    properties: {}
  - name: baggageclaim
    release: concourse
    properties: {}
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
